apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: dev
  labels:
    app: python
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: kevinjcloud/pyapp-gha:e453225
          ports:
            - containerPort: 8000
